#!/bin/bash
#Specify Schrodinger path

n= complex_ligand
#script needed to set cahin names fro ligand and receptor
#complex.pdb as initial receptor structure
#mv complex.pdb complex_unprocessed.pdb
$SCHRODINGER/utilities/prepwizard -disulfides -glycosylation -samplewater -propka_pH 7.0 -rmsd 0.3 complex_unprocessed.pdb complex.pdb
#identify and rename chains H,L vmd

#ligand.pdb as initial ligand structure
#mv ligand.pdb ligand_unprocessed.pdb
$SCHRODINGER/utilities/prepwizard -disulfides -glycosylation -samplewater -propka_pH 7.0 -rmsd 0.3 ligand_unprocessed.pdb ligand.pdb
#identify and rename chains C use vmd

#Antibody docking
$SCHRODINGER/run -FROM psp piper.py -jobname $n -receptor complex.pdb -receptor_chain L,H -poses 30 -rotations 70000 -OMPI 24 -JOBID -antibody -ligand ligand.pdb -ligand_chain C,P -use_nonstandard_residue yes

#convert docking output to pv
$SCHRODINGER/run pv_convert.py -mode split_pv $n-out.maegz

#run MMGBSA on pv
$SCHRODINGER/prime_mmgbsa -OVERWRITE -prime_opt OPLS_VERSION=S-OPLS $n-out-out_pv.maegz

wget https://raw.githubusercontent.com/KyllenD/antibody-design/main/extract_complex.py
$SCHRODINGER/run extract_complex.py $j-out.maegz `sort -n -k 2 -t "," $j-out-out-out.csv | head -n 1 | awk -F "," '{print $1}' | sed "s/$j//g" | sed 's/[^0-9]*//g'`
